import React from 'react';
import DisplayLinks from '../../components/DisplayLinks';

const Page: React.FC = (): React.ReactNode => {
  return (
    <main className="w-full h-full flex items-center justify-center flex-col gap-8">
      <section className="flex flex-col gap-4 w-full">
        <h1 className="text-5xl font-bold text-center text-[#593116] tracking-tighter break-normal whitespace-normal">
          Our links
        </h1>
        <p className="text-center text-[#593116] tracking-tight text-xl">
          View our links, generated by Links to display a gorgeous link-in-bio website.
        </p>
      </section>
      <DisplayLinks />
    </main>
  );
};

export default Page;